apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: storage-foundation
    rbac.deckhouse.io/aggregate-to-infrastructure-as: manager
    rbac.deckhouse.io/aggregate-to-storage-as: manager
    rbac.deckhouse.io/kind: manage
    rbac.deckhouse.io/level: module
    rbac.deckhouse.io/namespace: d8-storage-foundation
  name: d8:manage:permission:module:storage-foundation:edit
rules:
- apiGroups:
  - deckhouse.io
  resourceNames:
  - storage-foundation
  resources:
  - moduleconfigs
  verbs:
  - create
  - update
  - patch
  - delete
