apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: storage-foundation
    rbac.deckhouse.io/aggregate-to-infrastructure-as: viewer
    rbac.deckhouse.io/aggregate-to-storage-as: viewer
    rbac.deckhouse.io/kind: manage
    rbac.deckhouse.io/level: module
    rbac.deckhouse.io/namespace: d8-storage-foundation
  name: d8:manage:permission:module:storage-foundation:view
rules:
- apiGroups:
  - deckhouse.io
  resourceNames:
  - storage-foundation
  resources:
  - moduleconfigs
  verbs:
  - get
  - list
  - watch
