version: "2"
run:
  go: "1.25"
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dogsled
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: ST1005.*
      - path: (.+)\.go$
        text: should not use dot imports
      - path: (.+)\.go$
        text: don't use an underscore in package name
      - path: (.+)\.go$
        text: 'exported: .*'
      - path: (.+)\.go$
        text: QF1008.*
      - path: (.+)\.go$
        text: QF1003.*
      - path: (.+)\.go$
        text: SA1019.*
      - path: (.+)\.go$
        text: 'ifElseChain: .*'
      - path: (.+)\.go$
        text: .* always receives .*
      - path: (.+)\.go$
        text: result .* is never used
      - path: (.+)\.go$
        text: 'var-naming: avoid meaningless package names'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/deckhouse)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
