---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "d8-{{ .Chart.Name }}-dataexport-validation"
  annotations:
    werf.io/deploy-dependency-webhooks: state=ready,kind=Deployment,name=webhooks,namespace=d8-{{ .Chart.Name }}
    werf.io/deploy-dependency-service: state=present,kind=Service,name=webhooks,namespace=d8-{{ .Chart.Name }}
  labels:
    heritage: deckhouse
    module: storage-foundation
webhooks:
  - name: "d8-{{ .Chart.Name }}-dataexport-validation.storage.deckhouse.io"
    failurePolicy: Fail
    rules:
      - apiGroups: ["storage.deckhouse.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE"]
        resources: ["dataexports"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: "d8-{{ .Chart.Name }}"
        name: "webhooks"
        path: "/dataexport-validate"
      caBundle: {{ .Values.storageFoundation.internal.customWebhookCert.ca | b64enc | quote }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 10
