type: object
properties:
  logLevel:
    description: Уровень логирования компонентов модуля.
  highAvailability:
    description: |
      Ручное управление режимом отказоустойчивости.

      По умолчанию режим отказоустойчивости определяется автоматически. [Подробнее](../../../deckhouse-configure-global.html#parameters-highavailability) про режим отказоустойчивости.
