{{- define "data_source_validator_resources" }}
cpu: 10m
memory: 25Mi
{{- end }}

{{- if (.Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: data-source-validator
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "data-source-validator")) | nindent 2 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: data-source-validator
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
    - containerName: "data-source-validator"
      minAllowed:
        {{- include "data_source_validator_resources" . | nindent 8 }}
      maxAllowed:
        cpu: 200m
        memory: 100Mi
{{- end }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: data-source-validator
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "data-source-validator" )) | nindent 2 }}
spec:
  minAvailable: {{ include "helm_lib_is_ha_to_value" (list . 1 0) }}
  selector:
    matchLabels:
      app: data-source-validator
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: data-source-validator
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "data-source-validator")) | nindent 2 }}
spec:
  serviceName: data-source-validator
  replicas: 1
  selector:
    matchLabels:
      app: data-source-validator
  template:
    metadata:
      labels:
        app: data-source-validator
    spec:
      {{- include "helm_lib_priority_class" (tuple . "cluster-medium") | nindent 6 }}
      {{- include "helm_lib_node_selector" (tuple . "system") | nindent 6 }}
      {{- include "helm_lib_tolerations" (tuple . "system") | nindent 6 }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_nobody" . | nindent 6 }}
      imagePullSecrets:
        - name: {{ .Chart.Name }}-module-registry
      serviceAccountName: data-source-validator
      containers:
        - name: data-source-validator
          {{- include "helm_lib_module_container_security_context_pss_restricted_flexible" (dict "ro" true "seccompProfile" true) | nindent 10 }}
          image: {{ include "helm_lib_module_image" (list . "dataSourceValidator") }}
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--leader-election=false"
            - "--http-endpoint=:8080"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            failureThreshold: 2
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            periodSeconds: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
              name: http-endpoint
              protocol: TCP
          resources:
            requests:
              {{- include "helm_lib_module_ephemeral_storage_only_logs" . | nindent 14 }}
{{- if not ( .Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
              {{- include "data_source_validator_resources" . | nindent 14 }}
{{- end }}
