// /*
// Copyright YEAR Flant JSC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */

// Code generated by MockGen. DO NOT EDIT.
// Source: data_exporter_iface.go
//
// Generated by this command:
//
//	mockgen -typed -package mock -copyright_file ../../../../hack/boilerplate.txt -write_source_comment -destination=./../mock/data_exporter_iface.go -source=data_exporter_iface.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"

	common "github.com/deckhouse/storage-foundation/common"
)

// MockDataManagerAccessTimestampUpdater is a mock of DataManagerAccessTimestampUpdater interface.
type MockDataManagerAccessTimestampUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockDataManagerAccessTimestampUpdaterMockRecorder
	isgomock struct{}
}

// MockDataManagerAccessTimestampUpdaterMockRecorder is the mock recorder for MockDataManagerAccessTimestampUpdater.
type MockDataManagerAccessTimestampUpdaterMockRecorder struct {
	mock *MockDataManagerAccessTimestampUpdater
}

// NewMockDataManagerAccessTimestampUpdater creates a new mock instance.
func NewMockDataManagerAccessTimestampUpdater(ctrl *gomock.Controller) *MockDataManagerAccessTimestampUpdater {
	mock := &MockDataManagerAccessTimestampUpdater{ctrl: ctrl}
	mock.recorder = &MockDataManagerAccessTimestampUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataManagerAccessTimestampUpdater) EXPECT() *MockDataManagerAccessTimestampUpdaterMockRecorder {
	return m.recorder
}

// UpdateAccessTimestamp mocks base method.
func (m *MockDataManagerAccessTimestampUpdater) UpdateAccessTimestamp(ctx context.Context, operation common.Operation, resourceNamespace, resourceName string, timestamp time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccessTimestamp", ctx, operation, resourceNamespace, resourceName, timestamp)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccessTimestamp indicates an expected call of UpdateAccessTimestamp.
func (mr *MockDataManagerAccessTimestampUpdaterMockRecorder) UpdateAccessTimestamp(ctx, operation, resourceNamespace, resourceName, timestamp any) *MockDataManagerAccessTimestampUpdaterUpdateAccessTimestampCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessTimestamp", reflect.TypeOf((*MockDataManagerAccessTimestampUpdater)(nil).UpdateAccessTimestamp), ctx, operation, resourceNamespace, resourceName, timestamp)
	return &MockDataManagerAccessTimestampUpdaterUpdateAccessTimestampCall{Call: call}
}

// MockDataManagerAccessTimestampUpdaterUpdateAccessTimestampCall wrap *gomock.Call
type MockDataManagerAccessTimestampUpdaterUpdateAccessTimestampCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDataManagerAccessTimestampUpdaterUpdateAccessTimestampCall) Return(arg0 error) *MockDataManagerAccessTimestampUpdaterUpdateAccessTimestampCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDataManagerAccessTimestampUpdaterUpdateAccessTimestampCall) Do(f func(context.Context, common.Operation, string, string, time.Time) error) *MockDataManagerAccessTimestampUpdaterUpdateAccessTimestampCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDataManagerAccessTimestampUpdaterUpdateAccessTimestampCall) DoAndReturn(f func(context.Context, common.Operation, string, string, time.Time) error) *MockDataManagerAccessTimestampUpdaterUpdateAccessTimestampCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockDataManagerStatusExpiredSetter is a mock of DataManagerStatusExpiredSetter interface.
type MockDataManagerStatusExpiredSetter struct {
	ctrl     *gomock.Controller
	recorder *MockDataManagerStatusExpiredSetterMockRecorder
	isgomock struct{}
}

// MockDataManagerStatusExpiredSetterMockRecorder is the mock recorder for MockDataManagerStatusExpiredSetter.
type MockDataManagerStatusExpiredSetterMockRecorder struct {
	mock *MockDataManagerStatusExpiredSetter
}

// NewMockDataManagerStatusExpiredSetter creates a new mock instance.
func NewMockDataManagerStatusExpiredSetter(ctrl *gomock.Controller) *MockDataManagerStatusExpiredSetter {
	mock := &MockDataManagerStatusExpiredSetter{ctrl: ctrl}
	mock.recorder = &MockDataManagerStatusExpiredSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataManagerStatusExpiredSetter) EXPECT() *MockDataManagerStatusExpiredSetterMockRecorder {
	return m.recorder
}

// SetStatusExpired mocks base method.
func (m *MockDataManagerStatusExpiredSetter) SetStatusExpired(ctx context.Context, operation common.Operation, resourceNamespace, resourceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatusExpired", ctx, operation, resourceNamespace, resourceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatusExpired indicates an expected call of SetStatusExpired.
func (mr *MockDataManagerStatusExpiredSetterMockRecorder) SetStatusExpired(ctx, operation, resourceNamespace, resourceName any) *MockDataManagerStatusExpiredSetterSetStatusExpiredCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatusExpired", reflect.TypeOf((*MockDataManagerStatusExpiredSetter)(nil).SetStatusExpired), ctx, operation, resourceNamespace, resourceName)
	return &MockDataManagerStatusExpiredSetterSetStatusExpiredCall{Call: call}
}

// MockDataManagerStatusExpiredSetterSetStatusExpiredCall wrap *gomock.Call
type MockDataManagerStatusExpiredSetterSetStatusExpiredCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDataManagerStatusExpiredSetterSetStatusExpiredCall) Return(arg0 error) *MockDataManagerStatusExpiredSetterSetStatusExpiredCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDataManagerStatusExpiredSetterSetStatusExpiredCall) Do(f func(context.Context, common.Operation, string, string) error) *MockDataManagerStatusExpiredSetterSetStatusExpiredCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDataManagerStatusExpiredSetterSetStatusExpiredCall) DoAndReturn(f func(context.Context, common.Operation, string, string) error) *MockDataManagerStatusExpiredSetterSetStatusExpiredCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
