// /*
// Copyright YEAR Flant JSC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */

// Code generated by MockGen. DO NOT EDIT.
// Source: user_authorizer.go
//
// Generated by this command:
//
//	mockgen -typed -package mock -copyright_file ../../../../hack/boilerplate.txt -write_source_comment -destination=./../mock/user_authorizer.go -source=user_authorizer.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	common "github.com/deckhouse/storage-foundation/common"
)

// MockUserAuthorizer is a mock of UserAuthorizer interface.
type MockUserAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockUserAuthorizerMockRecorder
	isgomock struct{}
}

// MockUserAuthorizerMockRecorder is the mock recorder for MockUserAuthorizer.
type MockUserAuthorizerMockRecorder struct {
	mock *MockUserAuthorizer
}

// NewMockUserAuthorizer creates a new mock instance.
func NewMockUserAuthorizer(ctrl *gomock.Controller) *MockUserAuthorizer {
	mock := &MockUserAuthorizer{ctrl: ctrl}
	mock.recorder = &MockUserAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAuthorizer) EXPECT() *MockUserAuthorizerMockRecorder {
	return m.recorder
}

// AuthenticateUserByToken mocks base method.
func (m *MockUserAuthorizer) AuthenticateUserByToken(ctx context.Context, token string) (bool, string, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateUserByToken", ctx, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].([]string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// AuthenticateUserByToken indicates an expected call of AuthenticateUserByToken.
func (mr *MockUserAuthorizerMockRecorder) AuthenticateUserByToken(ctx, token any) *MockUserAuthorizerAuthenticateUserByTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateUserByToken", reflect.TypeOf((*MockUserAuthorizer)(nil).AuthenticateUserByToken), ctx, token)
	return &MockUserAuthorizerAuthenticateUserByTokenCall{Call: call}
}

// MockUserAuthorizerAuthenticateUserByTokenCall wrap *gomock.Call
type MockUserAuthorizerAuthenticateUserByTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserAuthorizerAuthenticateUserByTokenCall) Return(authenticated bool, username string, groups []string, err error) *MockUserAuthorizerAuthenticateUserByTokenCall {
	c.Call = c.Call.Return(authenticated, username, groups, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserAuthorizerAuthenticateUserByTokenCall) Do(f func(context.Context, string) (bool, string, []string, error)) *MockUserAuthorizerAuthenticateUserByTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserAuthorizerAuthenticateUserByTokenCall) DoAndReturn(f func(context.Context, string) (bool, string, []string, error)) *MockUserAuthorizerAuthenticateUserByTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AuthorizeUser mocks base method.
func (m *MockUserAuthorizer) AuthorizeUser(ctx context.Context, operation common.Operation, namespace, username string, groups []string) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizeUser", ctx, operation, namespace, username, groups)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AuthorizeUser indicates an expected call of AuthorizeUser.
func (mr *MockUserAuthorizerMockRecorder) AuthorizeUser(ctx, operation, namespace, username, groups any) *MockUserAuthorizerAuthorizeUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizeUser", reflect.TypeOf((*MockUserAuthorizer)(nil).AuthorizeUser), ctx, operation, namespace, username, groups)
	return &MockUserAuthorizerAuthorizeUserCall{Call: call}
}

// MockUserAuthorizerAuthorizeUserCall wrap *gomock.Call
type MockUserAuthorizerAuthorizeUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserAuthorizerAuthorizeUserCall) Return(allowed bool, reason string, err error) *MockUserAuthorizerAuthorizeUserCall {
	c.Call = c.Call.Return(allowed, reason, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserAuthorizerAuthorizeUserCall) Do(f func(context.Context, common.Operation, string, string, []string) (bool, string, error)) *MockUserAuthorizerAuthorizeUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserAuthorizerAuthorizeUserCall) DoAndReturn(f func(context.Context, common.Operation, string, string, []string) (bool, string, error)) *MockUserAuthorizerAuthorizeUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
