apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    heritage: deckhouse
    module: storage-foundation
    rbac.deckhouse.io/aggregate-to-storage-foundation-as: manager
    rbac.deckhouse.io/kind: use
  name: d8:use:capability:storage-foundation:manage_resources
rules:
  - apiGroups:
      - storage.deckhouse.io
    resources:
      - volumecapturerequests
      - volumerestorerequests
    verbs:
      - create
      - update
      - patch
      - delete
      - deletecollection
